#!/usr/bin/env python3
"""
calibrate_serial_hitl.py — HITL 校准, 直接产出 (dongle serial → 符号名) 映射.

跟现有 calibrate_can_mapping.py 的区别:
  - calibrate_can_mapping 产出 (USB bus-info → 符号名) → 写 activate_can.sh
  - 本脚本   产出 (USB iSerial → 符号名)        → 写 config/dongle_serials.yml

为什么需要这条新路径:
  USB bus-info 跟 USB 物理口位置绑定; 任何插拔/拆装都可能错位.
  USB iSerial 由 dongle 固件烧死, 只要 dongle 没换臂就稳定, 物理口任意.

流程:
  0. 探测当前所有 CAN ifaces + 各自 dongle iSerial (sysfs walk)
  1. 确保 4 个 iface 都 UP + bitrate (HITL 检测前置)
  2. 依次提示晃 4 个角色 (左 master/左 slave/右 master/右 slave),
     用 calibrate_can_mapping._identify_shaken_arm 同款检测逻辑识别 iface
  3. iface → serial → 符号名, 写 config/dongle_serials.yml
  4. 提示用户用 activate_can_v2.sh 激活

用法:
  python3 piper_tools/calibrate_serial_hitl.py            # 标准 HITL
  python3 piper_tools/calibrate_serial_hitl.py --activate # 校准完成后自动激活
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path

# 复用兄弟脚本的检测逻辑
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, SCRIPT_DIR)

from calibrate_can_mapping import _identify_shaken_arm  # noqa: E402

_HOST_PROFILE = os.path.join(
    PROJECT_ROOT, "config", "device_profiles", f"{os.uname().nodename.split('.')[0]}.yml"
)
CONFIG_PATH = (
    os.environ.get("KAI0_DEVICE_PROFILE")
    or (_HOST_PROFILE if os.path.isfile(_HOST_PROFILE)
        else os.path.join(PROJECT_ROOT, "config", "dongle_serials.yml"))
)
BITRATE = 1000000

# 角色顺序: 先两个 master (静止时安静, 用户拖动易识别), 再两个 slave.
ROLE_ASSIGN_SEQ = [
    ("can_left_mas",    "左 master (示教左臂)"),
    ("can_right_mas",   "右 master (示教右臂)"),
    ("can_left_slave",  "左 slave  (执行左臂)"),
    ("can_right_slave", "右 slave  (执行右臂)"),
]


def iface_serial(iface: str) -> str:
    """sysfs walk: /sys/class/net/<iface>/device → 沿父目录找 USB iSerial."""
    devlink = f"/sys/class/net/{iface}/device"
    if not os.path.exists(devlink):
        return ""
    cur = os.path.realpath(devlink)
    while cur and cur != "/":
        cand = os.path.join(cur, "serial")
        if os.path.isfile(cand):
            try:
                with open(cand) as f:
                    return f.read().strip()
            except OSError:
                return ""
        cur = os.path.dirname(cur)
    return ""


def list_can_ifaces() -> list[str]:
    out = subprocess.run(
        ["ip", "-br", "link", "show", "type", "can"],
        capture_output=True, text=True, timeout=5,
    )
    return [l.split()[0] for l in out.stdout.strip().split("\n") if l.strip()]


def ensure_up(iface: str) -> bool:
    """确保 iface UP 且 bitrate 已设置. 已经 UP 则跳过."""
    out = subprocess.run(
        ["ip", "-details", "link", "show", iface],
        capture_output=True, text=True, timeout=3,
    )
    text = out.stdout
    if "state UP" in text and "bitrate" in text:
        return True
    # 用 sudo 设 bitrate + up
    subprocess.run(["sudo", "ip", "link", "set", iface, "down"],
                   stderr=subprocess.DEVNULL)
    rc1 = subprocess.run(
        ["sudo", "ip", "link", "set", iface, "type", "can", "bitrate", str(BITRATE)],
        capture_output=True, text=True,
    ).returncode
    rc2 = subprocess.run(
        ["sudo", "ip", "link", "set", iface, "up"],
        capture_output=True, text=True,
    ).returncode
    return rc1 == 0 and rc2 == 0


def write_yaml(role_to_serial: dict, config_path: str):
    """Update only CAN role lines, preserving camera/chunk profile fields."""
    path = Path(config_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    existing = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    roles = {role for role, _ in ROLE_ASSIGN_SEQ}
    kept = [
        line for line in existing
        if line.split(":", 1)[0].strip() not in roles
    ]
    if not kept:
        kept = [
            "# Auto-generated by piper_tools/calibrate_serial_hitl.py",
            "# Maps canonical CAN iface name to gs_usb adapter iSerial.",
            "",
        ]
    while kept and not kept[-1].strip():
        kept.pop()
    kept.extend(["", "# CAN role mapping (updated by HITL calibration)"])
    for role, _ in ROLE_ASSIGN_SEQ:
        sn = role_to_serial.get(role)
        if sn:
            kept.append(f"{role}: '{sn}'")
    path.write_text("\n".join(kept) + "\n", encoding="utf-8")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--activate", action="store_true",
                    help="校准完成后自动调 activate_can_v2.sh")
    ap.add_argument("--config", default=CONFIG_PATH,
                    help="profile YAML to update (default: current hostname profile, else legacy dongle_serials.yml)")
    args = ap.parse_args()

    # ── 0. 探测 ifaces + serials ─────────────────────────────────────────
    ifaces = list_can_ifaces()
    print(f"=== 探测到 {len(ifaces)} 个 CAN iface ===")
    serial_map = {}   # iface → serial
    for i in ifaces:
        sn = iface_serial(i)
        serial_map[i] = sn
        print(f"  {i:22s} serial={sn or '<unreadable>'}")
    print()

    if len(ifaces) < 1:
        print("[FAIL] 没有检测到任何 CAN iface (dongle 未插/未上电?)")
        sys.exit(1)
    if len(ifaces) < 4:
        print(f"[WARN] 只检测到 {len(ifaces)} 个 CAN iface (满配 4). "
              f"不在位的角色可在下面逐个跳过, 只校准在位的臂。")
        print()
    if any(not s for s in serial_map.values()):
        print("[FAIL] 部分 iface 读不到 USB iSerial (非 gs_usb dongle?)")
        sys.exit(1)
    if len(set(serial_map.values())) != len(serial_map):
        print("[FAIL] serial 有重复 — sysfs walk 走错路径了, 排查吧")
        sys.exit(1)

    # ── 1. 确保所有 iface UP (HITL 检测需要 candump + SDK 都通) ──────────
    print(f"=== 确保 {len(ifaces)} 个 iface UP + bitrate ===")
    for i in ifaces:
        ok = ensure_up(i)
        flag = "✓" if ok else "✗"
        print(f"  {flag} {i}")
    print()

    # ── 2. HITL: 依次识别 4 个角色 ───────────────────────────────────────
    print("=" * 60)
    print("  HITL 校准: 依次晃 4 个角色, 脚本检测哪个 iface 在动")
    print("=" * 60)
    print()
    remaining = list(ifaces)
    role_to_serial = {}
    for role_iface, role_desc in ROLE_ASSIGN_SEQ:
        print(f"━━━ 角色: {role_iface}  ({role_desc}) ━━━")
        if not remaining:
            print(f"  [SKIP] 没有剩余 iface, 自动跳过 {role_iface}\n")
            continue
        # 允许跳过不在位的角色 (臂拆修/未接) — 只校准在位的臂
        resp = input(f"  该角色臂在位并可晃动? [Enter=开始识别 / s=跳过(不在位)]: ").strip().lower()
        if resp == "s":
            print(f"  [SKIP] {role_iface} 跳过 (臂不在位)\n")
            continue
        # _identify_shaken_arm 的第 2 个参数被用于显示 ("bus: X"),
        # 传 serial_map 让它打 "bus: <serial>" — 更直观
        identified = _identify_shaken_arm(remaining, serial_map, target_desc=role_desc)
        if identified is None:
            print(f"[ABORT] 在 {role_iface} 取消")
            sys.exit(2)
        sn = serial_map[identified]
        role_to_serial[role_iface] = sn
        print(f"  → {role_iface} ← iface={identified}  serial={sn}\n")
        remaining.remove(identified)

    # ── 3. 汇总 + 确认 + 写 YAML ─────────────────────────────────────────
    print("=" * 60)
    print("  校准结果汇总")
    print("=" * 60)
    for role, _ in ROLE_ASSIGN_SEQ:
        sn = role_to_serial.get(role)
        print(f"  {role:22s} → {sn if sn else '(跳过/不在位)'}")
    print()
    if not role_to_serial:
        print("[FAIL] 没有校准任何角色, 退出 (未写 YAML)。")
        sys.exit(1)
    if len(role_to_serial) < 4:
        print(f"[提示] 只校准了 {len(role_to_serial)}/4 个角色, YAML 只含在位的; "
              f"缺的角色 activate 时会告警跳过。")
    confirm = input(f"写入 {args.config}? [Y/n] ").strip().lower()
    if confirm not in ("", "y", "yes"):
        print("未保存, 退出.")
        sys.exit(0)
    write_yaml(role_to_serial, args.config)
    print(f"✓ 已写 {args.config}")

    # ── 4. 激活 ───────────────────────────────────────────────────────────
    if args.activate:
        print()
        print("=== 自动激活 ===")
        rc = subprocess.call(["bash", os.path.join(SCRIPT_DIR, "activate_can_v2.sh")])
        sys.exit(rc)
    else:
        print()
        print("下一步: bash piper_tools/activate_can_v2.sh")


if __name__ == "__main__":
    main()
